export const BOTTOM_TAB_CONTAINER_HEIGHT = 60;
export const BOTTOM_TAB_CONTAINER_SAFEAREA_HEIGHT = 25;
export const BOTTOM_TAB_PADDING_HORIZONTAL = 15;
export const BOTTOM_TAB_HEIGHT = 54;
export const BOTTOM_TAB_RADIUS = 27;
